# Use .txt file to specify the training, validation and test set
split_info:
  type: TextSplit
  train_split_file: train.txt
  val_split_file: val.txt
  test_type: TextSplit
  test_split_file: test.txt